import Link from "next/link";
import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "Stay Awhile And Listen",
  description: "Generated by Next and Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header>
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent"
          >
            <Image
              src="/images/BlackLogo.svg"
              alt="logo"
              width={91}
              height={63}
            />
          </Link>
        </header>

        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
